#ANDROID makefile in src

SRC_ROOT := $(call my-dir)
LOCAL_PATH := $(call my-dir)
SRC_ROOT := $(LOCAL_PATH)

include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/OpenThreads/pthreads/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osg/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgDB/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgUtil/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgGA/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgText/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgViewer/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgAnimation/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgFX/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgManipulator/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgParticle/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPresentation/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgShadow/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgSim/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgTerrain/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgWidget/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgVolume/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgWrappers/serializers/osg/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgWrappers/serializers/osgAnimation/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgWrappers/serializers/osgFX/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgWrappers/serializers/osgManipulator/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgWrappers/serializers/osgParticle/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgWrappers/serializers/osgSim/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgWrappers/serializers/osgShadow/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgWrappers/serializers/osgTerrain/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgWrappers/serializers/osgText/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgWrappers/serializers/osgVolume/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgWrappers/deprecated-dotosg/osg/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgWrappers/deprecated-dotosg/osgParticle/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgWrappers/deprecated-dotosg/osgAnimation/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgWrappers/deprecated-dotosg/osgFX/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgWrappers/deprecated-dotosg/osgSim/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgWrappers/deprecated-dotosg/osgText/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgWrappers/deprecated-dotosg/osgViewer/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgWrappers/deprecated-dotosg/osgShadow/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgWrappers/deprecated-dotosg/osgTerrain/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgWrappers/deprecated-dotosg/osgVolume/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgWrappers/deprecated-dotosg/osgWidget/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/osga/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/rot/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/scale/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/trans/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/normals/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/revisions/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/view/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/shadow/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/terrain/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/osg/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/ive/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/cfg/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/glsl/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/rgb/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/bmp/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/pnm/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/dds/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/tga/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/hdr/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/dot/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/vtf/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/jpeg/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/gif/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/png/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/tiff/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/gdal/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/ogr/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/3dc/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/p3d/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/curl/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/dw/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/bvh/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/x/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/dxf/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/OpenFlight/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/geo/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/obj/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/pic/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/stl/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/ac/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/pov/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/logo/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/lws/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/md2/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/osgtgz/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/tgz/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/shp/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/txf/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/bsp/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/mdl/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/lwo/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/ply/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/txp/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/freetype/Android.mk 
include /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osgPlugins/pvr/Android.mk 


