# Install script for directory: /home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/src/osg

# Set the install prefix
IF(NOT DEFINED CMAKE_INSTALL_PREFIX)
  SET(CMAKE_INSTALL_PREFIX "/usr/local")
ENDIF(NOT DEFINED CMAKE_INSTALL_PREFIX)
STRING(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
IF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  IF(BUILD_TYPE)
    STRING(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  ELSE(BUILD_TYPE)
    SET(CMAKE_INSTALL_CONFIG_NAME "")
  ENDIF(BUILD_TYPE)
  MESSAGE(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
ENDIF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)

# Set the component getting installed.
IF(NOT CMAKE_INSTALL_COMPONENT)
  IF(COMPONENT)
    MESSAGE(STATUS "Install component: \"${COMPONENT}\"")
    SET(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  ELSE(COMPONENT)
    SET(CMAKE_INSTALL_COMPONENT)
  ENDIF(COMPONENT)
ENDIF(NOT CMAKE_INSTALL_COMPONENT)

# Install shared libraries without execute permission?
IF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  SET(CMAKE_INSTALL_SO_NO_EXE "1")
ENDIF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "libopenscenegraph-dev")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/osg" TYPE FILE FILES
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/AlphaFunc"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/AnimationPath"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/ApplicationUsage"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/ArgumentParser"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Array"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/ArrayDispatchers"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/AudioStream"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/AutoTransform"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Billboard"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/BlendColor"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/BlendEquation"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/BlendFunc"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/BoundingBox"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/BoundingSphere"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/BoundsChecking"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/buffered_value"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/BufferIndexBinding"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/BufferObject"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Camera"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/CameraNode"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/CameraView"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/ClampColor"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/ClearNode"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/ClipNode"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/ClipPlane"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/ClusterCullingCallback"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/CollectOccludersVisitor"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/ColorMask"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/ColorMatrix"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/ComputeBoundsVisitor"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/ConvexPlanarOccluder"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/ConvexPlanarPolygon"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/CoordinateSystemNode"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/CopyOp"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/CullFace"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/CullingSet"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/CullSettings"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/CullStack"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/DeleteHandler"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Depth"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/DisplaySettings"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Drawable"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/DrawPixels"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Endian"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Export"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/fast_back_stack"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Fog"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/FragmentProgram"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/FrameBufferObject"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/FrameStamp"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/FrontFace"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Geode"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Geometry"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/GL"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/GL2Extensions"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/GLExtensions"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/GLBeginEndAdapter"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/GLObjects"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/GLU"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/GraphicsCostEstimator"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/GraphicsContext"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/GraphicsThread"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Group"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Hint"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Image"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/ImageSequence"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/ImageStream"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/ImageUtils"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/io_utils"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/KdTree"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Light"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/LightModel"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/LightSource"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/LineSegment"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/LineStipple"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/LineWidth"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/LOD"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/LogicOp"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Material"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Math"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Matrix"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Matrixd"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Matrixf"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/MatrixTransform"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/MixinVector"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Multisample"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Node"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/NodeCallback"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/NodeTrackerCallback"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/NodeVisitor"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Notify"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Object"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/observer_ptr"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Observer"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/ObserverNodePath"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/OccluderNode"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/OcclusionQueryNode"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/OperationThread"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/PagedLOD"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Plane"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Point"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/PointSprite"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/PolygonMode"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/PolygonOffset"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/PolygonStipple"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Polytope"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/PositionAttitudeTransform"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/PrimitiveSet"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Program"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Projection"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/ProxyNode"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Quat"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Referenced"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/ref_ptr"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/RenderInfo"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Scissor"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Sequence"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/ShadeModel"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Shader"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/ShaderAttribute"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/ShaderComposer"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/ShadowVolumeOccluder"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Shape"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/ShapeDrawable"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/State"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/StateAttribute"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/StateAttributeCallback"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/StateSet"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Stats"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Stencil"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/StencilTwoSided"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Switch"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/TemplatePrimitiveFunctor"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/TexEnv"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/TexEnvCombine"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/TexEnvFilter"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/TexGen"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/TexGenNode"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/TexMat"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Texture"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Texture1D"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Texture2D"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Texture2DMultisample"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Texture2DArray"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Texture3D"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/TextureCubeMap"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/TextureRectangle"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Timer"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/TransferFunction"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Transform"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/TriangleFunctor"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/TriangleIndexFunctor"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Uniform"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/UserDataContainer"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/ValueObject"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Vec2"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Vec2b"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Vec2d"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Vec2f"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Vec2s"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Vec3"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Vec3b"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Vec3d"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Vec3f"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Vec3s"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Vec4"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Vec4b"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Vec4d"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Vec4f"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Vec4s"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Vec4ub"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Version"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/VertexProgram"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/View"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Viewport"
    "/home/paulo/osgEarthAndroid/osgearth/OpenSceneGraph/include/osg/Config"
    )
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "libopenscenegraph-dev")

